### ISSUE TITLE
Overlap when media player ist active

### ISSUE THREAD

**Issue by derduesentrieb** [iCrazeiOS/ComplicationsFix#1]
When playing media, the media player is moved down with the complications in a weird way so that they overlap.
See the following image:

![IMG_0150](https://user-images.githubusercontent.com/36128165/211813110-9e42b062-5660-4663-b7c4-d8f59e945ec2.PNG)

iPhone 13 Pro
iOS 15.1.1
XinA15 Jailbreak

**Comment by iCrazeiOS** [comment]
https://easyupload.io/unq70q

Please try this build and see if it works for you

**Comment by iCrazeiOS** [comment]
Note that it may still look weird if you're on the lockscreen when the music player first shows up, but it should fix itself next time you go to the lockscreen

**Comment by burneikis** [comment]
https://github.com/AlexBurneikis/ComplicationsFixFix

I fixed the bug (not super clean method but works)

**Comment by derduesentrieb** [comment]
> https://github.com/AlexBurneikis/ComplicationsFixFix
> 
> I fixed the bug (not super clean method but works)

Thank you! Works for me as well. Apparently the original dev is working on an official fix but that's great for the meantime as it's the only good lock screen launcher for iOS 15.

**Comment by iCrazeiOS** [comment]
> https://github.com/AlexBurneikis/ComplicationsFixFix
> 
> I fixed the bug (not super clean method but works)

you fine with me merging the two fixes? will credit & add to control file ofc

**Comment by burneikis** [comment]
Go for it mate!

**Comment by iCrazeiOS** [comment]
both fixes are now merged.
repo has been updated, compiled build available on https://repo.icrazeios.com
